CREATE TABLE IF NOT EXISTS public.user_room_access (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "roomId" integer NOT NULL,
  active boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_room_access_user_fk FOREIGN KEY ("userId") REFERENCES public.users(id),
  CONSTRAINT user_room_access_room_fk FOREIGN KEY ("roomId") REFERENCES public.rooms(id),
  CONSTRAINT user_room_access_user_room_unique UNIQUE ("userId", "roomId")
);

CREATE INDEX IF NOT EXISTS user_room_access_user_idx ON public.user_room_access ("userId");
CREATE INDEX IF NOT EXISTS user_room_access_room_idx ON public.user_room_access ("roomId");

INSERT INTO public.user_room_access ("userId", "roomId", active)
SELECT id, "roomId", true
FROM public.users
WHERE "roomId" IS NOT NULL
ON CONFLICT ("userId", "roomId") DO UPDATE SET active = true;
